<?php
# Add shortcode Site Header
vc_map(array(
	'name' 				=> esc_html__("DOWNLOAD CART", 'wpdance'),
	'base' 				=> 'tvlgiao_wpdance_download_cart',
	'description' 		=> esc_html__("DISPLAY DOWNLOAD CART", 'wpdance'),
	'category' 			=> esc_html__("WPDance", 'wpdance'),
	'params' => array(
		array(
			'type' 			=> 'textfield',
			'class' 		=> '',
			'heading' 		=> esc_html__("Class", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'class',
			'value' 		=> ''
		),
		array(
			'type' 			=> 'textfield',
			'class' 		=> '',
			'heading' 		=> esc_html__("ID", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'id',
			'value' 		=> ''
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("Style", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'style',
			'value' 		=> array('Default'=>'default'),
		)
	)
));
vc_map(array(
	'name' 				=> esc_html__("Custom Downloads", 'wpdance'),
	'base' 				=> 'custom_downloads',
	'description' 		=> esc_html__("Use display content of download .", 'wpdance'),
	'category' 			=> esc_html__("WPDance", 'wpdance'),
	'params' => array(
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("Style", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'style',
			'value' 		=> array('Default'=>'default','Style 1'=>'one_big','Style 2'=>'first_row'),
		),
		array(
			'type' 			=> 'textfield',
			'class' 		=> '',
			'heading' 		=> esc_html__("Number", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'number',
			'value' 		=> '9',
		),
		array(
			'type' 			=> 'textfield',
			'class' 		=> '',
			'heading' 		=> esc_html__("columns", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'columns',
			'value' 		=> '3',
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("orderby", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'orderby',
			'value' 		=> array('date'=>'post_date','price'=>'price','title'=>'title','id'=>'id','random'=>'random','post in'=>'post__in','sale'=>'sale'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("order", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'order',
			'value' 		=> array('DESC'=>'DESC','ASC'=>'ASC'),
		),
		array(
			'type' 			=> 'textfield',
			'class' 		=> '',
			'heading' 		=> esc_html__("IDS", 'wpdance'),
			'description'	=> esc_html__("use id of post type download ,the example : 12,13,30", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'ids',
			'value' 		=> '',
		),
		array(
			'type' 			=> 'textfield',
			'class' 		=> '',
			'heading' 		=> esc_html__("category", 'wpdance'),
			'description'	=> esc_html__("use slug of category ,the example : category1,category2,category3", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'category',
			'value' 		=> '',
		),
		array(
			'type' 			=> 'textfield',
			'class' 		=> '',
			'heading' 		=> esc_html__("exclude category", 'wpdance'),
			'description'	=> esc_html__("use slug of category ,the example : category1,category2,category3", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'exclude_category',
			'value' 		=> '',
		),
		array(
			'type' 			=> 'textfield',
			'class' 		=> '',
			'heading' 		=> esc_html__("tags", 'wpdance'),
			'description'	=> esc_html__("use slug of Tags ,the example : tags1,tags2,tags3", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'tags',
			'value' 		=> '',
		),
		array(
			'type' 			=> 'textfield',
			'class' 		=> '',
			'heading' 		=> esc_html__("exclude tags", 'wpdance'),
			'description'	=> esc_html__("use slug of Tags ,the example : tags1,tags2,tags3", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'exclude_tags',
			'value' 		=> '',
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("relation", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'relation',
			'value' 		=> array('OR'=>'OR','AND'=>'AND'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("pagination", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'pagination',
			'value' 		=> array('True'=>'true','False'=>'false'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("thumbnails", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'thumbnails',
			'value' 		=> array('True'=>'true','False'=>'false'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("price", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'price',
			'value' 		=> array('No'=>'no','Yes'=>'yes'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("excerpt", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'excerpt',
			'value' 		=> array('Yes'=>'yes','No'=>'no'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("author", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'author',
			'value' 		=> array('Yes'=>'yes','No'=>'no'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("full content", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'full_content',
			'value' 		=> array('No'=>'no','Yes'=>'yes'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("buy_button", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			'param_name' 	=> 'buy_button',
			'value' 		=> array('Yes'=>'yes','No'=>'no'),
		),
		#custom one big 
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("thumbnails", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			"dependency"		=> array( 'element' => "style", 'value' => 'one_big' ),
			'group'		=> 'Product Large',
			'param_name' 	=> 'thumbnails_large',
			'value' 		=> array('True'=>'true','False'=>'false'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("price", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			"dependency"		=> array( 'element' => "style", 'value' => 'one_big' ),
			'group'		=> 'Product Large',
			'param_name' 	=> 'price_large',
			'value' 		=> array('No'=>'no','Yes'=>'yes'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("excerpt", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			"dependency"		=> array( 'element' => "style", 'value' => 'one_big' ),
			'group'		=> 'Product Large',
			'param_name' 	=> 'excerpt_large',
			'value' 		=> array('Yes'=>'yes','No'=>'no'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("author", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			"dependency"		=> array( 'element' => "style", 'value' => 'one_big' ),
			'group'		=> 'Product Large',
			'param_name' 	=> 'author_lagre',
			'value' 		=> array('Yes'=>'yes','No'=>'no'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("full content", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			"dependency"		=> array( 'element' => "style", 'value' => 'one_big' ),
			'group'		=> 'Product Large',
			'param_name' 	=> 'full_content_large',
			'value' 		=> array('No'=>'no','Yes'=>'yes'),
		),
		array(
			'type' 			=> 'dropdown',
			'class' 		=> '',
			'heading' 		=> esc_html__("buy_button", 'wpdance'),
			'description'	=> esc_html__("", 'wpdance'),
			'admin_label' 	=> true,
			"dependency"		=> array( 'element' => "style", 'value' => 'one_big' ),
			'group'		=> 'Product Large',
			'param_name' 	=> 'buy_button_large',
			'value' 		=> array('Yes'=>'yes','No'=>'no'),
		),

	)
));
?>